from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

from config import STATS_FILE

_CATEGORY_LABELS = {
    "newsletters": "Newsletters",
    "promotions": "Promotions & Sale Alerts",
    "social": "Social Notifications",
    "automated": "Automated / Digests",
    "spam": "Spam",
    "other": "Other",
}

_GROUP_COLORS = ["#f9f9f9", "#ffffff"]


def format_digest_html(junk_emails: list[dict], scan_date: str) -> str:
    """Formats junk emails into an HTML digest.

    Groups by category, shows top 20 per category, saves stats to data/stats.json.
    """
    # Ensure data directory exists
    Path(STATS_FILE).parent.mkdir(parents=True, exist_ok=True)

    header = f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:960px;margin:40px auto;color:#333;font-size:14px">
  <h2 style="color:#cc3333;margin-bottom:4px">Gmail Cleanup — Weekly Digest</h2>
  <p style="color:#666;margin-top:0">Scan date: <strong>{scan_date[:10]}</strong>
     &nbsp;|&nbsp; Junk emails found: <strong>{len(junk_emails)}</strong></p>
"""

    if not junk_emails:
        html = header + """  <p style="color:#2e7d32;font-size:16px">Your inbox is clean — no junk found!</p>
</body></html>"""
        _save_stats(scan_date, junk_emails, {})
        return html

    groups: dict[str, list[dict]] = defaultdict(list)
    for email in junk_emails:
        groups[email.get("category", "other")].append(email)

    table_rows = ""
    total_shown = 0
    total_hidden = 0

    for color_idx, (category, emails) in enumerate(groups.items()):
        label = _CATEGORY_LABELS.get(category, category.title())
        bg = _GROUP_COLORS[color_idx % 2]
        shown_count = min(20, len(emails))
        hidden_count = len(emails) - shown_count
        total_shown += shown_count
        total_hidden += hidden_count

        group_header = (
            f'<tr><td colspan="4" style="padding:10px 8px 4px;font-weight:bold;'
            f'background:{bg};border-top:2px solid #ddd;color:#555;font-size:12px;'
            f'text-transform:uppercase;letter-spacing:0.5px">'
            f'{label} ({len(emails)})</td></tr>'
        )
        table_rows += group_header

        for email in emails[:20]:
            sender = email["sender"][:55]
            subject = email["subject"][:80]
            date = email["date"][:16]
            reason = email.get("reason", "")
            table_rows += (
                f'<tr style="background:{bg}">'
                f'<td style="padding:6px 8px;border-bottom:1px solid #eee;max-width:200px;overflow:hidden">{sender}</td>'
                f'<td style="padding:6px 8px;border-bottom:1px solid #eee">{subject}</td>'
                f'<td style="padding:6px 8px;border-bottom:1px solid #eee;white-space:nowrap;color:#555">{date}</td>'
                f'<td style="padding:6px 8px;border-bottom:1px solid #eee;color:#888;font-size:12px">{reason}</td>'
                f'</tr>'
            )

        if hidden_count > 0:
            table_rows += (
                f'<tr style="background:{bg}">'
                f'<td colspan="4" style="padding:6px 8px;border-bottom:1px solid #eee;color:#999;font-size:12px;font-style:italic">'
                f'+ {hidden_count} more in this category</td></tr>'
            )

    table = f"""  <table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:16px">
    <thead>
      <tr style="background:#eee;text-align:left">
        <th style="padding:10px 8px">From</th>
        <th style="padding:10px 8px">Subject</th>
        <th style="padding:10px 8px">Date</th>
        <th style="padding:10px 8px">Reason</th>
      </tr>
    </thead>
    <tbody>{table_rows}</tbody>
  </table>"""

    footer = f"""  <div style="margin-top:24px;padding:14px 18px;background:#fff8e1;border-left:4px solid #ffc107;border-radius:3px">
    To review and approve deletions, run:<br>
    <code style="font-size:14px;display:inline-block;margin-top:6px">python main.py approve</code>
  </div>

  <div style="margin-top:20px;padding:12px;background:#f5f5f5;border-radius:3px;font-size:12px;color:#666">
    <strong>Summary:</strong> {total_shown} emails shown, {total_hidden} more available<br>
    <em>See console output for classification token usage and cost details.</em>
  </div>

  <p style="color:#bbb;font-size:11px;margin-top:32px">Generated by Gmail Cleanup &nbsp;|&nbsp; Emails are moved to Trash, not permanently deleted.</p>
</body></html>"""

    html = header + table + "\n" + footer

    # Save cumulative stats
    _save_stats(scan_date, junk_emails, groups)

    return html


def _save_stats(scan_date: str, junk_emails: list[dict], by_category: dict[str, list[dict]]) -> None:
    """Saves cumulative stats to data/stats.json."""
    stats_file = Path(STATS_FILE)
    stats_file.parent.mkdir(parents=True, exist_ok=True)

    # Load existing stats or start fresh
    if stats_file.exists():
        stats = json.loads(stats_file.read_text())
    else:
        stats = {"scans": [], "total_junk": 0, "total_by_category": {}}

    # Add this scan's data
    scan_record = {
        "scan_date": scan_date,
        "total_junk": len(junk_emails),
        "by_category": {cat: len(emails) for cat, emails in by_category.items()},
    }
    stats["scans"].append(scan_record)
    stats["total_junk"] += len(junk_emails)

    for category, emails in by_category.items():
        stats["total_by_category"][category] = stats["total_by_category"].get(category, 0) + len(emails)

    # Keep only last 10 scans to prevent huge file
    if len(stats["scans"]) > 10:
        stats["scans"] = stats["scans"][-10:]

    stats_file.write_text(json.dumps(stats, indent=2))
    print(f"Saved cumulative stats to {stats_file}", file=sys.stderr)
